wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.13
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1649432639
    t:
      1:
      - 55
      3:
      - 17
      - 19
      4: 3.7.13
      5: 0.12.13
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0002
