wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1648702972
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      3:
      - 1
      - 2
      4: 3.7.13
      5: 0.12.11
      6: 4.17.0
      8:
      - 1
      - 5
