wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1649761050
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      3:
      - 17
      - 19
      4: 3.7.13
      5: 0.12.14
      6: 4.18.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value:
    eval: 32
    test: 128
    train: 128
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 6.0e-05
